services:
  - type: web
    name: sign-language-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
