services:
  - type: web
    name: sign-language-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    plan: free
